POST http://localhost:5000/products
Content-Type: application/json

{
  "name": "Microondas",
  "image": "https://http2.mlstatic.com/D_NQ_NP_2X_800188-MLB81543657912_012025-T-micro-ondas-midea-27l-220v-mxsa27p-branco-e-preto.webp",
  "price": 249.90,
  "location": "Rio de Janeiro, RJ",
  
}
